<a href="https://colab.research.google.com/github/faishalwickson/LVQ_Neupy/blob/main/LVQ_neupy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install neupy

     |████████████████████████████████| 235kB 5.1MB/s 
     |████████████████████████████████| 92.7MB 53kB/s 
     |████████████████████████████████| 51kB 5.2MB/s 
     |████████████████████████████████| 368kB 45.3MB/s 
     |████████████████████████████████| 3.2MB 44.8MB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1
  Found existing installation: progressbar2 3.38.0
    Uninstalling progressbar2-3.38.0:
      Successfully uninstalled progressbar2-3.38.0


In [ ]:
from sklearn import metrics
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score

In [ ]:
import numpy as np
from neupy import algorithms

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

In [ ]:
# X = np.array([[0, 0], [0, 1], [1, 0], [1, 1], [2, 2], [1, 2]])
# y = np.array([0, 0, 0, 1, 1, 1])

In [ ]:
pip install tensorflow

In [ ]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
# from keras.models import Sequential
# from keras.layers import Dense

In [ ]:
#input dataset
df = pd.read_csv('uts-sisdas.csv')
df

no_obs   x1   x2   x3  kelas
0        1  6.7  6.5  5.9      1
1        2  7.2  7.2  6.7      1
2        4  6.3  6.0  5.7      1
3        6  5.8  5.8  5.6      1
4        7  6.4  6.4  6.3      1
5        8  5.2  5.1  4.7      1
6       10  6.4  6.4  6.1      1
7       12  6.2  6.6  7.0      2
8       13  3.7  4.6  5.5      2
9       14  6.4  6.8  6.8      2
10      17  5.2  6.0  5.4      2
11      18  5.0  4.9  5.1      2
12      20  5.6  6.3  6.8      2
13      22  3.9  4.6  5.4      3
14      23  2.8  4.0  4.4      3
15      24  3.9  5.0  5.2      3
16      25  4.0  4.5  4.4      3
17      26  4.0  4.8  5.5      3
18      29  3.7  4.6  5.7      3
19      31  6.1  5.7  5.4      1
20      32  6.7  7.1  6.7      1
21      34  7.0  6.6  6.4      1
22      36  6.5  5.9  5.7      1
23      37  5.4  5.5  5.4      1
24      38  6.1  5.7  5.8      1
25      40  6.3  6.1  5.4      1
26      42  6.5  6.7  5.8      2
27      43  5.8  6.4  5.9      2
28      44  5.6  5.8  5.5      2
29      47  6.2  6.8  7.3      2
30      48  5.5  5.9  6.4      2
31      50  6.6  7.1  6.5      2
32      52  4.2  4.7  4.7      3
33      53  4.4  5.8  6.4      3
34      54  3.9  4.4  5.0      3
35      55  3.8  4.3  4.3      3
36      56  4.1  4.2  4.2      3
37      59  3.4  4.2  4.2      3

In [ ]:
#Hapus atribut no_obs
df = df.drop(columns='no_obs')

In [ ]:
#Konvert nilai kelas ke [0,2] sesuai format pada neupy
df.kelas[df.kelas == 1] = 0
df.kelas[df.kelas == 2] = 1
df.kelas[df.kelas == 3] = 2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from 

In [ ]:
#mengubah format dataset
dataset = df.values
dataset

array([[6.7, 6.5, 5.9, 0. ],
       [7.2, 7.2, 6.7, 0. ],
       [6.3, 6. , 5.7, 0. ],
       [5.8, 5.8, 5.6, 0. ],
       [6.4, 6.4, 6.3, 0. ],
       [5.2, 5.1, 4.7, 0. ],
       [6.4, 6.4, 6.1, 0. ],
       [6.2, 6.6, 7. , 1. ],
       [3.7, 4.6, 5.5, 1. ],
       [6.4, 6.8, 6.8, 1. ],
       [5.2, 6. , 5.4, 1. ],
       [5. , 4.9, 5.1, 1. ],
       [5.6, 6.3, 6.8, 1. ],
       [3.9, 4.6, 5.4, 2. ],
       [2.8, 4. , 4.4, 2. ],
       [3.9, 5. , 5.2, 2. ],
       [4. , 4.5, 4.4, 2. ],
       [4. , 4.8, 5.5, 2. ],
       [3.7, 4.6, 5.7, 2. ],
       [6.1, 5.7, 5.4, 0. ],
       [6.7, 7.1, 6.7, 0. ],
       [7. , 6.6, 6.4, 0. ],
       [6.5, 5.9, 5.7, 0. ],
       [5.4, 5.5, 5.4, 0. ],
       [6.1, 5.7, 5.8, 0. ],
       [6.3, 6.1, 5.4, 0. ],
       [6.5, 6.7, 5.8, 1. ],
       [5.8, 6.4, 5.9, 1. ],
       [5.6, 5.8, 5.5, 1. ],
       [6.2, 6.8, 7.3, 1. ],
       [5.5, 5.9, 6.4, 1. ],
       [6.6, 7.1, 6.5, 1. ],
       [4.2, 4.7, 4.7, 2. ],
       [4.4, 5.8, 6.4, 2. ],
       [3.9, 4

In [ ]:
# Pilih 3 kolom pertama untuk dijadikan sebagai atribut
X = dataset[:,0:3]
# Pilih 1 kolom terakhir sebagai label
y = dataset[:,3:4]

In [ ]:
#Lakukan normalisasi untuk meningkatkan performa dan akurasi
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.88636364, 0.78125   , 0.5483871 ],
       [1.        , 1.        , 0.80645161],
       [0.79545455, 0.625     , 0.48387097],
       [0.68181818, 0.5625    , 0.4516129 ],
       [0.81818182, 0.75      , 0.67741935],
       [0.54545455, 0.34375   , 0.16129032],
       [0.81818182, 0.75      , 0.61290323],
       [0.77272727, 0.8125    , 0.90322581],
       [0.20454545, 0.1875    , 0.41935484],
       [0.81818182, 0.875     , 0.83870968],
       [0.54545455, 0.625     , 0.38709677],
       [0.5       , 0.28125   , 0.29032258],
       [0.63636364, 0.71875   , 0.83870968],
       [0.25      , 0.1875    , 0.38709677],
       [0.        , 0.        , 0.06451613],
       [0.25      , 0.3125    , 0.32258065],
       [0.27272727, 0.15625   , 0.06451613],
       [0.27272727, 0.25      , 0.41935484],
       [0.20454545, 0.1875    , 0.48387097],
       [0.75      , 0.53125   , 0.38709677],
       [0.88636364, 0.96875   , 0.80645161],
       [0.95454545, 0.8125    , 0.70967742],
       [0.

In [ ]:
#Split dataset menjadi datatrain dan datatest dengan perbandingan 7:3
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

In [ ]:
#melakukan training menggunakan neupy sebanyak 20 epochs dengan learning rate 0,01
lvqnet = algorithms.LVQ3(n_inputs=3, n_classes=3, step=0.01)
lvqnet.train(X_train, Y_train, epochs=20)

In [ ]:
#prediksi datatest
predicted = lvqnet.predict(X_test)
predicted

array([0, 2, 1, 1, 2, 1, 0, 2, 2, 1, 1, 2])

In [ ]:
#Evaluation
def print_metrics(labels, preds):
    print("Precision Score: {}".format(precision_score(labels,
           preds, average = 'weighted')))
    print("Recall Score: {}".format(recall_score(labels, preds,
           average = 'weighted')))
    print("Accuracy Score: {}".format(accuracy_score(labels,
           preds)))
    print("F1 Score: {}".format(f1_score(labels, preds, average =
           'weighted')))

In [ ]:
#Membandingkan datatest dengan prediksi untuk mendapatkan metrics
print_metrics(Y_test, predicted)

Precision Score: 0.875
Recall Score: 0.8333333333333334
Accuracy Score: 0.8333333333333334
F1 Score: 0.8434343434343434


In [ ]:
#input dataset baru
df0 = pd.read_csv('uts-sisdas-kosong.csv')
df0

no_obs   x1   x2   x3  kelas
0        3  6.2  6.2  6.1    NaN
1        5  5.9  5.9  5.7    NaN
2        9  5.9  6.1  5.6    NaN
3       11  6.2  6.8  7.5    NaN
4       15  6.6  6.4  4.6    NaN
5       16  6.1  6.7  5.8    NaN
6       19  5.0  5.6  5.8    NaN
7       11  6.2  6.8  7.5    NaN
8       21  2.7  3.7  4.6    NaN
9       27  4.0  4.6  5.1    NaN
10      28  3.4  4.6  4.6    NaN
11      30  4.4  4.8  4.6    NaN
12      33  5.5  5.2  5.1    NaN
13      35  6.5  6.3  5.7    NaN
14      39  6.1  6.1  5.5    NaN
15      41  6.1  7.1  7.2    NaN
16      45  2.5  3.2  5.3    NaN
17      46  3.4  4.2  3.1    NaN
18      49  7.0  8.0  7.7    NaN
19      51  4.1  3.7  3.9    NaN
20      57  4.7  6.0  6.5    NaN
21      58  3.9  3.8  4.6    NaN
22      60  4.0  3.9  3.5    NaN

In [ ]:
# df0 = df0.drop(columns='kelas')

In [ ]:
dataset0 = df0.values
X_val = dataset0[:,1:4]

In [ ]:
X_val

array([[6.2, 6.2, 6.1],
       [5.9, 5.9, 5.7],
       [5.9, 6.1, 5.6],
       [6.2, 6.8, 7.5],
       [6.6, 6.4, 4.6],
       [6.1, 6.7, 5.8],
       [5. , 5.6, 5.8],
       [6.2, 6.8, 7.5],
       [2.7, 3.7, 4.6],
       [4. , 4.6, 5.1],
       [3.4, 4.6, 4.6],
       [4.4, 4.8, 4.6],
       [5.5, 5.2, 5.1],
       [6.5, 6.3, 5.7],
       [6.1, 6.1, 5.5],
       [6.1, 7.1, 7.2],
       [2.5, 3.2, 5.3],
       [3.4, 4.2, 3.1],
       [7. , 8. , 7.7],
       [4.1, 3.7, 3.9],
       [4.7, 6. , 6.5],
       [3.9, 3.8, 4.6],
       [4. , 3.9, 3.5]])

In [ ]:
#Normalisasi
min_max_scaler = preprocessing.MinMaxScaler()
X_valnorm = min_max_scaler.fit_transform(X_val)
X_valnorm

array([[0.82222222, 0.625     , 0.65217391],
       [0.75555556, 0.5625    , 0.56521739],
       [0.75555556, 0.60416667, 0.54347826],
       [0.82222222, 0.75      , 0.95652174],
       [0.91111111, 0.66666667, 0.32608696],
       [0.8       , 0.72916667, 0.58695652],
       [0.55555556, 0.5       , 0.58695652],
       [0.82222222, 0.75      , 0.95652174],
       [0.04444444, 0.10416667, 0.32608696],
       [0.33333333, 0.29166667, 0.43478261],
       [0.2       , 0.29166667, 0.32608696],
       [0.42222222, 0.33333333, 0.32608696],
       [0.66666667, 0.41666667, 0.43478261],
       [0.88888889, 0.64583333, 0.56521739],
       [0.8       , 0.60416667, 0.52173913],
       [0.8       , 0.8125    , 0.89130435],
       [0.        , 0.        , 0.47826087],
       [0.2       , 0.20833333, 0.        ],
       [1.        , 1.        , 1.        ],
       [0.35555556, 0.10416667, 0.17391304],
       [0.48888889, 0.58333333, 0.73913043],
       [0.31111111, 0.125     , 0.32608696],
       [0.

In [ ]:
#Prediksi menggunakan model training
predict0 = lvqnet.predict(X_valnorm)
predict0

array([0, 0, 0, 1, 0, 0, 1, 1, 2, 1, 2, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       2])

In [ ]:
#Cetak hasil prediksi dengan memasukkan kembali pada dataset
df0.kelas = predict0
df0

no_obs   x1   x2   x3  kelas
0        3  6.2  6.2  6.1      0
1        5  5.9  5.9  5.7      0
2        9  5.9  6.1  5.6      0
3       11  6.2  6.8  7.5      1
4       15  6.6  6.4  4.6      0
5       16  6.1  6.7  5.8      0
6       19  5.0  5.6  5.8      1
7       11  6.2  6.8  7.5      1
8       21  2.7  3.7  4.6      2
9       27  4.0  4.6  5.1      1
10      28  3.4  4.6  4.6      2
11      30  4.4  4.8  4.6      0
12      33  5.5  5.2  5.1      0
13      35  6.5  6.3  5.7      0
14      39  6.1  6.1  5.5      0
15      41  6.1  7.1  7.2      1
16      45  2.5  3.2  5.3      2
17      46  3.4  4.2  3.1      2
18      49  7.0  8.0  7.7      1
19      51  4.1  3.7  3.9      2
20      57  4.7  6.0  6.5      1
21      58  3.9  3.8  4.6      2
22      60  4.0  3.9  3.5      2

In [ ]:
df0.kelas[df.kelas == 0] = 1
df0.kelas[df.kelas == 1] = 2
df0.kelas[df.kelas == 2] = 3
df0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid 

no_obs   x1   x2   x3  kelas
0        3  6.2  6.2  6.1      1
1        5  5.9  5.9  5.7      1
2        9  5.9  6.1  5.6      1
3       11  6.2  6.8  7.5      1
4       15  6.6  6.4  4.6      1
5       16  6.1  6.7  5.8      1
6       19  5.0  5.6  5.8      1
7       11  6.2  6.8  7.5      2
8       21  2.7  3.7  4.6      2
9       27  4.0  4.6  5.1      2
10      28  3.4  4.6  4.6      2
11      30  4.4  4.8  4.6      2
12      33  5.5  5.2  5.1      2
13      35  6.5  6.3  5.7      3
14      39  6.1  6.1  5.5      3
15      41  6.1  7.1  7.2      3
16      45  2.5  3.2  5.3      3
17      46  3.4  4.2  3.1      3
18      49  7.0  8.0  7.7      3
19      51  4.1  3.7  3.9      1
20      57  4.7  6.0  6.5      1
21      58  3.9  3.8  4.6      1
22      60  4.0  3.9  3.5      1